//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NigeriaSchoolsNewage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string geo_zone_ID { get; set; }
        public string state_ID { get; set; }
        public string lga_ID { get; set; }
        public string year_established { get; set; }
        public string school_ownership_ID { get; set; }
        public string school_type_ID { get; set; }
        public string school_subtype_ID { get; set; }
    }
}
